[package]
name = "ya_psd"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.0.0"
encoding_rs = "0.8.28"
once_cell = "1.8.0"
anyhow = "1.0.43"
